"""add characteristics and embedding to artists

Revision ID: ed911727f8df
Revises: 350924e5945f
Create Date: 2026-09-15 15:12:17.123163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ed911727f8df'
down_revision: Union[str, Sequence[str], None] = '350924e5945f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector's column type requires the extension to exist first - not tracked by
    # autogenerate, added by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('artists', sa.Column('characteristics', sa.JSON(), nullable=True))
    op.add_column('artists', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'embedding')
    op.drop_column('artists', 'characteristics')
    # ### end Alembic commands ###
